2.9
{
    "filename": "links-2.9.tar.gz",
    "md5": "8987fcf5178ac021ec47ccaf9330bd25",
    "sha1": "ae591159bdcf15dd173c292021e3691917cdae78",
    "sha256": "e2d4e193eb3147f0d745e28d37d510edb22697707e329cbe361bb79037bae332"
}

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -4,57 +4,53 @@
 # This file is a part of the Links program, released under GPL.
 
 make=make
-if which gmake 2>/dev/null >/dev/null && gmake --version | grep -i "GNU Make" >/dev/null
-then
-echo Found GNU Make under gmake. Going to use gmake instead of make.
-make=gmake
+if which gmake 2>/dev/null >/dev/null && gmake --version | grep -i "GNU Make" >/dev/null; then
+	echo Found GNU Make under gmake. Going to use gmake instead of make.
+	make=gmake
 fi
 
-if which automake-1.4 2>/dev/null >/dev/null
-then
-automake="automake-1.4"
+if which automake-1.4 2>/dev/null >/dev/null; then
+	automake="automake-1.4"
 else
-automake="automake"
+	automake="automake"
 fi
 
-if which aclocal-1.4 2>/dev/null >/dev/null
-then
-aclocal="aclocal-1.4"
-if [ -d /usr/share/aclocal-1.4/ ]; then
-	aclocal="$aclocal --acdir=/usr/share/aclocal-1.4/"
-fi
+if which aclocal-1.4 2>/dev/null >/dev/null; then
+	aclocal="aclocal-1.4"
+	if [ -d /usr/share/aclocal-1.4/ ]; then
+		aclocal="$aclocal --acdir=/usr/share/aclocal-1.4/"
+	fi
 else
-aclocal="aclocal"
-fi
-
-if which autoconf2.13 2>/dev/null >/dev/null
-then
-autoconf="autoconf2.13"
-else
-autoconf="autoconf"
+	aclocal="aclocal"
 fi
 
-if which autoheader2.13 2>/dev/null >/dev/null
-then
-autoheader="autoheader2.13"
+if which autoconf2.13 2>/dev/null >/dev/null; then
+	autoconf="autoconf2.13"
+elif which autoconf-2.13 2>/dev/null >/dev/null; then
+	autoconf="autoconf-2.13"
 else
-autoheader="autoheader"
+	autoconf="autoconf"
+fi
+
+if which autoheader2.13 2>/dev/null >/dev/null; then
+	autoheader="autoheader2.13"
+elif which autoheader-2.13 2>/dev/null >/dev/null; then
+	autoheader="autoheader-2.13"
+else
+	autoheader="autoheader"
 fi
 
 if [ "$1" = reconf ]; then
-	if ! which pkg-config 2>/dev/null >/dev/null
-	then
-	echo Warning: You don\'t have pkg-config. The PKG_CHECK_MODULES macro will probably fail. >&2	
+	if ! which pkg-config 2>/dev/null >/dev/null; then
+		echo Warning: You don\'t have pkg-config. The PKG_CHECK_MODULES macro will probably fail. >&2	
 	fi
 
-	if ! which $autoconf 2>/dev/null >/dev/null
-	then
+	if ! which $autoconf 2>/dev/null >/dev/null; then
 		echo You don\'t have autoconf. Wiping out. >&2
 		exit 1
 	fi
 
-	if ! $autoconf --version | grep -i "GNU Autoconf" >/dev/null
-	then
+	if ! $autoconf --version | grep -i "GNU Autoconf" >/dev/null; then
 		echo This looks like autoconf installed on OpenBSD. >&2
 		if ! AUTOCONF_VERSION=2.13 $autoconf --version 2>/dev/null >/dev/null
 		then
@@ -134,7 +130,7 @@ export CFLAGS="-Wall -g -O2 -pipe -ansi -U__STRICT_ANSI__ -fno-common $CFLAGS" &
 export CXXFLAGS="$CXXFLAGS -Wall -g -O2 -pipe" &&
 ./configure --enable-graphics --enable-debuglevel=2 &&
 $make clean &&
-$make &&
+$make -j2 &&
 if [ "$1" = reconf ]; then
 	$autoheader &&
 	$automake --add-missing --include-deps --build-dir=. --srcdir-name=. --output-dir=. &&
